version: '3.1'
services:

  mysql-docker:
    image: mysql:8.0
    container_name: final-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
          - ps

  redis-docker:
    image: redis/redis-stack:latest
    container_name: final-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on:
      - mysql-docker
    networks:
      - ps

  final-docker:
    build:
      context: .
    container_name: final-app
    depends_on:
      - mysql-docker
    networks:
      - ps

networks:
  ps:
